## Exercise
##### At the same level as this notebook on github, there is an Exercise folder that contains carprices.csv. This file has car sell prices for 3 different models. First plot data points on a scatter plot chart to see if linear regression model can be applied. If yes, then build a model that can answer following questions,

##### 1) Predict price of a mercedez benz that is 4 yr old with mileage 45000
##### 2) Predict price of a BMW X5 that is 7 yr old with mileage 86000
##### 3) Tell me the score (accuracy) of your model. (Hint: use LinearRegression().score())

In [8]:
import pandas as pd
car = pd.read_csv('carprices.csv')
car

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [12]:
dummies = pd.get_dummies(car['Car Model'])
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [16]:
afterdummies = dummies.replace({True:1,False:0})
afterdummies

C:\Users\SAAD COMMUNICATION\AppData\Local\Temp\ipykernel_12304\2801705084.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  afterdummies = dummies.replace({True:1,False:0})

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [24]:
merged = pd.concat([car,afterdummies],axis='columns')
merged

,Car Model,Mileage,Sell Price($),Age(yrs),Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,0,1,0
1,BMW X5,35000,34000,3,0,1,0
2,BMW X5,57000,26100,5,0,1,0
3,BMW X5,22500,40000,2,0,1,0
4,BMW X5,46000,31500,4,0,1,0
5,Audi A5,59000,29400,5,1,0,0
6,Audi A5,52000,32000,5,1,0,0
7,Audi A5,72000,19300,6,1,0,0
8,Audi A5,91000,12000,8,1,0,0
9,Mercedez Benz C class,67000,22000,6,0,0,1
10,Mercedez Benz C class,83000,20000,7,0,0,1
11,Mercedez Benz C class,79000,21000,7,0,0,1
12,Mercedez Benz C class,59000,33000,5,0,0,1

In [28]:
final = merged.drop(['Car Model','Mercedez Benz C class'],axis='columns')
final

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [32]:
X = final.drop(['Sell Price($)'],axis='columns').values
X

array([[69000,     6,     0,     1],
       [35000,     3,     0,     1],
       [57000,     5,     0,     1],
       [22500,     2,     0,     1],
       [46000,     4,     0,     1],
       [59000,     5,     1,     0],
       [52000,     5,     1,     0],
       [72000,     6,     1,     0],
       [91000,     8,     1,     0],
       [67000,     6,     0,     0],
       [83000,     7,     0,     0],
       [79000,     7,     0,     0],
       [59000,     5,     0,     0]], dtype=int64)

In [36]:
y = final['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [40]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [42]:
model.fit(X,y)

LinearRegression()

##### The score (accuracy) of the model

In [52]:
model.score(X,y)

0.9417050937281082

##### Price of mercedez benz that is 4 yr old with mileage 45000

In [54]:
model.predict([[45000,4,0,0]])

array([36991.31721061])

##### Price of BMW X5 that is 7 yr old with mileage 86000

In [58]:
model.predict([[86000,7,0,1]])

array([11080.74313219])